### PR TITLE
Save the whole network state, including optimizer, scheduler and iteration progress

### PR DESCRIPTION
**Pull request by FeepingCreature**
Saving just the models is not enough to reload later. Also, without restoring the iteration offset, the TensorBoard progress will look weird.

### CODE REVIEW

**Comment by FeepingCreature** [comment]
Update: the z_test state should be saved too, so the preview pics are continuous.

**Comment by AlexiaJM** [comment]
Wow, I had no idea we could do this! So one can simply stop it at any time after a save and continue later retaining the seed and everything. Thank you ^-^.

**Comment by FeepingCreature** [comment]
Hm, slightly late question: does it make more sense to save i and go "from here to plus 100000 again" or say "no, only train to the specified limit starting from last save?"

Ie. when specifying a 100k run, and resuming at i=55k, run for another 100k or for 45k? I originally did "another 100k" but am increasingly coming around to 45k.

**Comment by AlexiaJM** [comment]
Oh right, it should only finish the rest.

**Comment by FeepingCreature** [comment]
Wonder what happens if I push an already merged branch.

edit: Apparently, nothing. Aww.

**Pull request merged**
